### ISSUE TITLE
Lighthouse errors on start in Binja 3.0

### ISSUE THREAD

**Issue by mkrasnitski** [gaasedelen/lighthouse#118]
There's been a new stable release of Binja which comes with what I'm assuming are many breaking changes. On startup, Lighthouse errors with the following trace:

    Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._load_module of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x7fc0452bc1c0>>
    Traceback (most recent call last):
      File "/opt/binaryninja/plugins/../python/binaryninja/scriptingprovider.py", line 854, in _load_module
        __import__(module + "." + plugin.subdir.replace("/", "."))
      File "/home/michael/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/__init__.py", line 19, in <module>
        from lighthouse.util.log import logging_started, start_logging
      File "/home/michael/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/__init__.py", line 3, in <module>
        from .debug import *
      File "/home/michael/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/debug.py", line 6, in <module>
        from .log import lmsg
      File "/home/michael/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/log.py", line 6, in <module>
        from .disassembler import disassembler
      File "/home/michael/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/disassembler/__init__.py", line 42, in <module>
        raise NotImplementedError("Unknown or unsupported disassembler!")
    NotImplementedError: Unknown or unsupported disassembler!

**Comment by mkrasnitski** [comment]
After some further digging, this is caused by an import error, where the `binaryninjaui` module can't be imported, which results in no `QtGui` implementation being imported either.
