### ISSUE TITLE
Successfully loaded 1 coverage file but ZeroDivisionError: float division by zero in coverage_table.py

### ISSUE THREAD

**Issue by k3vinlusec** [gaasedelen/lighthouse#131]
Hi,

I install Lighthouse plugin in IDA Pro 8.2 macOS version. After I load a coverage log from drrun, I encounter the following error.
The hit blocks have been highlighted, the coverage overview windows can't pop up due to the following error. Could you help check it? Thanks!

Python 3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
[Lighthouse] Enabling painting...
[Lighthouse] Successfully loaded 1 coverage file(s)...
Traceback (most recent call last):
  File "/Users/kailu/.idapro/plugins/lighthouse/integration/ida_integration.py", line 343, in activate
    self.action_function()
  File "/Users/kailu/.idapro/plugins/lighthouse/integration/core.py", line 395, in interactive_load_file
    self.open_coverage_overview(lctx.dctx)
  File "/Users/kailu/.idapro/plugins/lighthouse/integration/core.py", line 208, in open_coverage_overview
    disassembler.show_dockable("Coverage Overview")
  File "/Users/kailu/.idapro/plugins/lighthouse/util/disassembler/ida_api.py", line 174, in show_dockable
    widget = make_dockable(dockable_name, parent, dctx)
  File "/Users/kailu/.idapro/plugins/lighthouse/integration/core.py", line 51, in create_coverage_overview
    overview = CoverageOverview(lctx, widget)
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_overview.py", line 39, in __init__
    self._ui_init()
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_overview.py", line 84, in _ui_init
    self._ui_init_table()
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_overview.py", line 97, in _ui_init_table
    self._table_view = CoverageTableView(self._table_controller, self._table_model, self.widget)
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_table.py", line 37, in __init__
    self._ui_init()
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_table.py", line 102, in _ui_init
    self._ui_init_table()
  File "/Users/kailu/.idapro/plugins/lighthouse/ui/coverage_table.py", line 193, in _ui_init_table
    tweak = (17*get_dpi_scale() - spacing)/get_dpi_scale()
ZeroDivisionError: float division by zero

**Comment by binjo** [comment]
The `fm.height()` appears smaller than `173.0` in certain resolutions, leads to `get_dpi_scale` returns a `0`, and in turn raises the `ZeroDivisionError` exception.
https://github.com/gaasedelen/lighthouse/blob/develop/plugins/lighthouse/util/qt/util.py#L63-L72
```python
def get_dpi_scale():
    """
    Get a DPI-afflicted value useful for consistent UI scaling.
    """
    font = MonospaceFont()
    font.setPointSize(normalize_to_dpi(120))
    fm = QtGui.QFontMetricsF(font)

    # xHeight is expected to be 40.0 at normal DPI
    return int(fm.height() / 173.0)
```

```
Python>import PyQt5.QtGui as QtGui
Python>font = QtGui.QFont("Courier New")
Python>font.setStyleHint(QtGui.QFont.Monospace)
Python>font.setPointSize(122)
Python>fm = QtGui.QFontMetricsF(font)
Python>fm.height()
138.1875
```

FWIW, I simply updated `173.0` to `40.0` and fixed the error, not sure it breaks ui or other, it just works for me.

**Comment by gaasedelen** [comment]
Ah ok, it looks like this is actually a regression from 6e1dcb8. I thought it was weird that dpi scale would be returning an int... that's now how I remember writing that logic.

The correct fix is to revert that line, so we return a float from get_dpi_scale(). And then go around and touch up any width/height dimension fields derived from that to force them into integers. I'll see if I can go through those cases tomorrow.
