### ISSUE TITLE
Lighthouse does not load in Binary Ninja as of 4.2.6456

### ISSUE THREAD

**Issue by novafacing** [gaasedelen/lighthouse#149]
The DockHandler/DockWidget APIs have been removed as of 4.2.6456, so Lighthouse will no longer load in Binary Ninja dev. I took a crack at starting a fix in #148 but it's not complete or tested.

**Comment by novafacing** [comment]
This would be fixed by #148, I've tested it and everything seems (?) to be working.

**Comment by tosanjay** [comment]
Hi,

I tried installing Lighthouse plugin in Binary Ninja 5.2.8722 (on Linux). But It does not work. see the error log below.

```
[ScriptingProvider] Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._load_module of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x7d92a3a078b0>>
[ScriptingProvider] Traceback (most recent call last):
[ScriptingProvider]   File "/binaryninja_commercial_linux/binaryninja/plugins/../python/binaryninja/scriptingprovider.py", line 1099, in _load_module
[ScriptingProvider]     __import__(module + "." + plugin.subdir.replace("/", "."))
[ScriptingProvider]   File "~/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/__init__.py", line 19, in <module>
[ScriptingProvider]     from lighthouse.util.log import logging_started, start_logging
[ScriptingProvider]   File "~/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/__init__.py", line 3, in <module>
[ScriptingProvider]     from .debug import *
[ScriptingProvider]   File "~/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/debug.py", line 6, in <module>
[ScriptingProvider]     from .log import lmsg
[ScriptingProvider]   File "~/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/log.py", line 6, in <module>
[ScriptingProvider]     from .disassembler import disassembler
[ScriptingProvider]   File "~/.binaryninja/repositories/community/plugins/gaasedelen_lighthouse/binjastub/../plugins/lighthouse/util/disassembler/__init__.py", line 42, in <module>
[ScriptingProvider]     raise NotImplementedError("Unknown or unsupported disassembler!")
[ScriptingProvider] NotImplementedError: Unknown or unsupported disassembler!
[Plugin Repository: community] Failed to load plugin: gaasedelen_lighthouse

```===========
Is there any work around?
