### ISSUE TITLE
Port to IDA 7.4 with Python 3 / no deprecated API

### ISSUE THREAD

**Issue by saidelike** [gaasedelen/lighthouse#73]
Atm it doesn't work with Python 3:

```
C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\plugins\lighthouse_plugin.py: Missing parentheses in call to 'print'. Did you mean print(prefix_message)? (log.py, line 21)
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 590, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins/lighthouse_plugin.py", line 1, in <module>
    from lighthouse.util.log import logging_started, start_logging
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\__init__.py", line 3, in <module>
    from .log import lmsg, logging_started, start_logging
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins\lighthouse\util\log.py", line 21
    print prefix_message
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(prefix_message)?
```

I haven't checked for the deprecated APIs but that would need to be checked too.

**Comment by gaasedelen** [comment]
All done! #79
