### ISSUE TITLE
Error within IDA Home

### ISSUE THREAD

**Issue by Stolas** [gaasedelen/lighthouse#88]
```[Lighthouse] Enabling painting...
Traceback (most recent call last):
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\integration\ida_integration.py", line 343, in activate
    self.action_function()
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\integration\core.py", line 338, in interactive_load_file
    lctx = self.get_context(dctx)
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\integration\ida_integration.py", line 55, in get_context
    lctx.start()
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\context.py", line 57, in start
    self.painter.start()
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\painting\painter.py", line 114, in start
    self.set_enabled(True)
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\painting\painter.py", line 140, in set_enabled
    self._notify_status_changed(enabled)
  File "C:/Program Files/IDA Home (PC) 7.5/plugins\lighthouse\painting\ida_painter.py", line 156, in _notify_status_changed
    if idaapi.init_hexrays_plugin():
AttributeError: module 'idaapi' has no attribute 'init_hexrays_plugin'```

A try-except around it fixes it.

**Comment by gaasedelen** [comment]
This is kind of amazing. Apparently, you might possibly be one of the first people to try and use lighthouse without a decompiler present in several years.. Not that it matters much, decompiler support is only a small plus on top of the rest of the plugin.

Thanks for the report, i'll get this fixed.

**Comment by Stolas** [comment]
The try except around it fixes it. I've had loads of plugins work funky on home edition, maybe I am the only cheapskate that uses IDA Home with plugins xD

**Comment by gaasedelen** [comment]
Thanks again, this should no be resolved on the dev branch... hopefully 😅
